apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
data:
  .dockerconfigjson:
type: kubernetes.io/dockerconfigjson


kubectl create secret generic regcreccd --from-file=.dockerconfigjson=C:\Users\isaqu\.docker\config.json --type=kubernetes.io/dockerconfigjson