apiVersion: v1
# Kind for volume chain
kind: PersistentVolume
metadata:
  # Name the persistent chain
  name: post-pv
  namespace: db-postegs
  # Labels for identifying PV
  labels:
    type: local
    app: post-pv
spec:
  storageClassName: standard
  capacity:
    # PV Storage capacity
    storage: 8Gi
  # A db can write and read from volumes to multiple pods
  accessModes:
    - ReadWriteMany
  # Specify the path to persistent the volumes
  hostPath:
    path: '/data/db'
