apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-pvc
  namespace: db-postegs
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  selector: 
    matchLabels:
      type: post-pv
