apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  labels:
    type: logs-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: logs-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  labels:
    type: media-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: media-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  labels:
    type: static-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: static-pv
