apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    type: logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/your/logs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    type: media-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/your/media
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  labels:
    type: static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/your/static
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
