apiVersion: v1
kind: ConfigMap
metadata:
  name: hercules-configmap
data:
  TZ: America/Cuiaba
  LANG: pt_BR.UTF-8
  LANGUAGE: pt_BR.UTF-8

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DJANGO_DEBUG: '0'
  DJANGO_ALLOWED_HOSTS: 'localhost'
  DJANGO_TRUSTED_ORIGINS: ''
  DJANGO_SECRET_KEY: 'django-security-code'
  DJANGO_LANGUAGE_CODE: 'pt-br'
  DJANGO_CACHE: 'redis'
  DJANGO_CACHE_REDIS_URL: 'redis://service.redis-server.svc.cluster.local'

---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  NGINX_SERVER_HOSTNAME: ''
  NGINX_SECRET_MEDIA_PATH: 'secret-files'

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_HOST: 'postgres://service.postgresdb.svc.cluster.local'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'testUser'
  POSTGRES_PASSWORD: 'testPassword'
  POSTGRES_DB: 'testDB'
