name: Docker Compose Actions Workflow
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker image ls
      - name: Test
        run: docker run --network container:hercules-python-web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3333/login?next=/
